# activate this profile when running the app in AWS ElasticBeanstalk
spring:
  data:
    redis:
      #      host: "ip-10-0-0-54.ap-south-1.compute.internal"
#      host: "manthan-redis-cache-0001-001.manthan-redis-cache.gupcp0.aps1.cache.amazonaws.com"
      host: "spring-redis-sample-cache-001.gupcp0.0001.aps1.cache.amazonaws.com"
      port: "6379"